package com.cwh.ssm.mapper;

import com.cwh.ssm.beans.Department;
import com.cwh.ssm.beans.DepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_department
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    long countByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_department
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    int deleteByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_department
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_department
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_department
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    List<Department> selectByExampleWithRowbounds(DepartmentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_department
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    List<Department> selectByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_department
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_department
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    int updateByExample(@Param("record") Department record, @Param("example") DepartmentExample example);
}