package com.cwh.ssm.mapper;

import com.cwh.ssm.beans.Employee;
import com.cwh.ssm.beans.EmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_employee
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    long countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_employee
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_employee
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_employee
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_employee
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    List<Employee> selectByExampleWithRowbounds(EmployeeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_employee
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    List<Employee> selectByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_employee
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_employee
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);


}