package com.cwh.ssm.beans;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_employee.id
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_employee.last_name
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_employee.gender
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_employee.email
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_employee.department_id
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    private Integer departmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_employee.id
     *
     * @return the value of table_employee.id
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_employee.id
     *
     * @param id the value for table_employee.id
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_employee.last_name
     *
     * @return the value of table_employee.last_name
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_employee.last_name
     *
     * @param lastName the value for table_employee.last_name
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_employee.gender
     *
     * @return the value of table_employee.gender
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_employee.gender
     *
     * @param gender the value for table_employee.gender
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_employee.email
     *
     * @return the value of table_employee.email
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_employee.email
     *
     * @param email the value for table_employee.email
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_employee.department_id
     *
     * @return the value of table_employee.department_id
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_employee.department_id
     *
     * @param departmentId the value for table_employee.department_id
     *
     * @mbg.generated Sat Aug 03 17:25:32 CST 2019
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }
}